# Generated by Django 5.2.7 on 2025-10-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingtypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingtype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Savings Account Type', 'verbose_name_plural': 'Savings Account Types'},
        ),
    ]
