# Generated by Django 5.2.7 on 2026-01-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingtypes', '0002_alter_savingtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtype',
            name='can_guarantee',
            field=models.BooleanField(default=True, help_text='Can this savings account be used as collateral for a loan?'),
        ),
    ]
