# Generated by Django 6.0.1 on 2026-04-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loanapplications", "0001_initial"),
        ("loanproducts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="loanproducts.loanproduct",
            ),
        ),
    ]
