# Generated by Django 5.2.7 on 2025-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Ready for Submission', 'Ready for Submission'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
