# Generated by Django 5.2.7 on 2025-11-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0003_loanapplication_repayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
