# Generated by Django 5.2.7 on 2025-11-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0004_loanapplication_total_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='self_guaranteed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
