# Generated by Django 5.2.7 on 2026-01-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0005_loanapplication_self_guaranteed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for Amendment', 'Ready for Amendment'), ('Amended', 'Amended'), ('In Progress', 'In Progress'), ('Ready for Submission', 'Ready for Submission'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
