# Generated by Django 5.2.7 on 2026-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0006_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='amendment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
