# Generated by Django 5.2.7 on 2025-10-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'SavingsAccount', 'verbose_name_plural': 'Savings Accounts'},
        ),
    ]
