# Generated by Django 5.2.7 on 2025-11-03 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guarantors', '0001_initial'),
        ('loanapplications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='guarantors.guarantorprofile')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_requests', to='loanapplications.loanapplication')),
            ],
            options={
                'verbose_name': 'Guarantee Request',
                'verbose_name_plural': 'Guarantee Requests',
                'ordering': ['-created_at'],
                'unique_together': {('loan_application', 'guarantor')},
            },
        ),
    ]
