# Generated by Django 5.2.7 on 2025-11-04 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteerequests', '0001_initial'),
        ('loanapplications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteerequest',
            name='guaranteed_amount',
            field=models.DecimalField(decimal_places=2, default='2000', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guaranteerequest',
            name='member',
            field=models.ForeignKey(default='192cf447-b3a3-443f-b2f0-f35f43121aca', on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guaranteerequest',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loanapplications.loanapplication'),
        ),
    ]
