# Generated by Django 5.2.7 on 2025-11-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteerequests', '0002_guaranteerequest_guaranteed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteerequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
