# Generated by Django 5.2.7 on 2026-01-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guaranteerequests', '0003_guaranteerequest_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteerequest',
            name='guaranteed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
