# Generated by Django 5.2.7 on 2026-01-15 06:07

import django.db.models.deletion
import loanpayments.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanaccounts', '0008_loanaccount_total_loan_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking'), ('Standing Order', 'Standing Order')], default='Mpesa', max_length=80)),
                ('repayment_type', models.CharField(choices=[('Regular Repayment', 'Regular Repayment'), ('Standing Order', 'Standing Order'), ('Interest Payment', 'Interest Payment'), ('Individual Settlement', 'Individual Settlement'), ('Early Settlement', 'Early Settlement'), ('Partial Payment', 'Partial Payment')], default='Regular Repayment', max_length=70)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=80)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_code', models.CharField(default=loanpayments.utils.generate_loan_payment_code, editable=False, max_length=76, unique=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments', to='loanaccounts.loanaccount')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Payment',
                'verbose_name_plural': 'Loan Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
