# Generated by Django 5.2.7 on 2026-01-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsdeposit',
            name='callback_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='payment_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='payment_status_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
