# Generated by Django 5.2.7 on 2026-01-15 12:55

import savingsdeposits.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0002_savingsdeposit_callback_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='identity',
            field=models.CharField(default=savingsdeposits.utils.generate_identity, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='savingsdeposit',
            name='payment_method',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('Mpesa STK Push', 'Mpesa STK Push'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Banking', 'Mobile Banking'), ('Standing Order', 'Standing Order')], default='Cash', max_length=100),
        ),
    ]
