# Generated by Django 5.2.7 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0003_alter_savingsdeposit_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
