# Generated by Django 5.2.7 on 2026-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsdeposits', '0004_alter_savingsdeposit_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED'), ('REVERSED', 'REVERSED')], default='PENDING', max_length=20),
        ),
    ]
