# Generated by Django 6.0.1 on 2026-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanpenalties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpenalty',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original penalty amount (20% of the total installment due)', max_digits=10, null=True),
        ),
    ]
