# Generated by Django 5.2.7 on 2026-01-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
