# Generated by Django 6.0.1 on 2026-07-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_employment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bookkeeper',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sacco_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_treasurer',
        ),
    ]
