# Generated by Django 5.2.7 on 2026-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='developerowino@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
