# Generated by Django 5.2.7 on 2025-11-03 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuarantorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_eligible', models.BooleanField(default=False, help_text='Admin has approved this member to be a guarantor')),
                ('eligibility_checked_at', models.DateTimeField(blank=True, null=True)),
                ('max_active_guarantees', models.PositiveIntegerField(default=3, help_text='Max number of loans this member can guarantee')),
                ('max_guarantee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Max total amount this member can guarantee', max_digits=15)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guarantor Profile',
                'verbose_name_plural': 'Guarantor Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
