# Generated by Django 5.2.7 on 2025-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantorprofile',
            name='max_guarantee_amount',
        ),
        migrations.AlterField(
            model_name='guarantorprofile',
            name='max_active_guarantees',
            field=models.PositiveIntegerField(default='2', help_text='Max number of loans this member can guarantee'),
        ),
    ]
