# Generated by Django 5.2.7 on 2025-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0002_remove_guarantorprofile_max_guarantee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantorprofile',
            name='max_guarantee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max total amount this member can guarantee', max_digits=15),
        ),
    ]
