# Generated by Django 5.2.7 on 2025-11-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0004_guarantorprofile_committed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantorprofile',
            name='committed_amount',
        ),
    ]
