# Generated by Django 5.2.7 on 2025-11-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0005_remove_guarantorprofile_committed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantorprofile',
            name='committed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
