# Generated by Django 5.2.7 on 2025-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0006_guarantorprofile_committed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantorprofile',
            name='committed_amount',
        ),
        migrations.AlterField(
            model_name='guarantorprofile',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guarantorprofile',
            name='max_active_guarantees',
            field=models.PositiveIntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='guarantorprofile',
            name='max_guarantee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
