# Generated by Django 5.2.7 on 2025-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0007_remove_guarantorprofile_committed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantorprofile',
            name='committed_guarantee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
