# Generated by Django 5.2.7 on 2025-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantors', '0008_guarantorprofile_committed_guarantee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantorprofile',
            name='max_active_guarantees',
            field=models.PositiveIntegerField(default=3, help_text='Max number of loans this member can guarantee'),
        ),
    ]
