# Generated by Django 6.0.1 on 2026-04-22 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeaccounts', '0001_initial'),
        ('feetypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeaccount',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='feetypes.feetype'),
        ),
        migrations.AddField(
            model_name='feeaccount',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
