# Generated by Django 6.0.1 on 2026-07-12 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feepayments', '0002_alter_feepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='transaction_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The actual date of the transaction', null=True),
        ),
    ]
