# Generated by Django 5.2.7 on 2025-11-01 11:56

import django.db.models.deletion
import loanaccounts.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanproducts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('account_number', models.CharField(default=loanaccounts.utils.generate_loan_account_number, max_length=20, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_interest_calulation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Defaulted', 'Defaulted')], default='Active', max_length=20)),
                ('total_interest_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_accounts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loanproducts.loanproduct')),
            ],
            options={
                'verbose_name': 'Loan Account',
                'verbose_name_plural': 'Loan Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
