# Generated by Django 5.2.7 on 2025-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Funded', 'Funded'), ('Closed', 'Closed'), ('Defaulted', 'Defaulted')], default='Active', max_length=20),
        ),
    ]
