# Generated by Django 6.0.1 on 2026-04-22 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loanaccounts", "0001_initial"),
        ("loanapplications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccount",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_account",
                to="loanapplications.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
