# Generated by Django 5.2.7 on 2025-11-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0002_alter_loanaccount_status'),
        ('loanapplications', '0004_loanapplication_total_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='loanapplications.loanapplication'),
        ),
    ]
