# Generated by Django 6.0.1 on 2026-04-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanaccounts', '0002_initial'),
        ('loanproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loanproducts.loanproduct'),
        ),
    ]
