# Generated by Django 5.2.7 on 2025-11-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0003_loanaccount_application'),
        ('loanapplications', '0004_loanapplication_total_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='loanapplications.loanapplication'),
        ),
    ]
