# Generated by Django 5.2.7 on 2026-01-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0004_alter_loanaccount_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='outstanding_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
