# Generated by Django 5.2.7 on 2026-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0005_alter_loanaccount_outstanding_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
