# Generated by Django 5.2.7 on 2026-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0006_alter_loanaccount_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=15),
            preserve_default=False,
        ),
    ]
