# Generated by Django 5.2.7 on 2026-01-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0007_alter_loanaccount_outstanding_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='total_loan_amount',
            field=models.DecimalField(decimal_places=2, default=600000, max_digits=15),
            preserve_default=False,
        ),
    ]
