# Generated by Django 5.2.7 on 2025-11-01 11:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('interest_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually')], default='Monthly', help_text='How interest is calculated', max_length=50)),
                ('calculation_schedule', models.CharField(choices=[('Fixed', 'Fixed Calendar (e.g., 1st of month)'), ('Relative', 'Relative to Loan Start Date'), ('Flexible', 'Custom/Flexible Schedule')], default='relative', help_text='Defines when interest is calculated (fixed calendar, loan start date, or custom).', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
