# Generated by Django 5.2.7 on 2025-11-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='calculation_schedule',
            field=models.CharField(choices=[('Fixed', 'Fixed Calendar (e.g., 1st of month)'), ('Relative', 'Relative to Loan Start Date'), ('Flexible', 'Custom/Flexible Schedule')], default='Relative', help_text='Defines when interest is calculated (fixed calendar, loan start date, or custom).', max_length=20),
        ),
    ]
